### ISSUE TITLE
Migrate project to the Camunda Community Hub?

### ISSUE THREAD

**Issue by celanthe** [amalagaura/camunda-workflow#50]
Hello! I hope today finds you well! My name is Rin Oliver, and I'm a Technical Community Builder at Camunda. I'm opening this issue today to ask if you might be interested in migrating this extension over to the [Camunda Community Hub](https://github.com/camunda-community-hub/community)?

We'd love to hear your feedback on how we might improve the overall community extension development process for maintainers and contributors moving forward, and learn more about what you'd like to see from this initiative in the future.

If migrating this extension something you'd be interested in, I can send you the instructions for doing so via email, or whatever communication method works best for you. If you are for any reason no longer able to maintain this extension, if it is migrated to the Hub I would be more than happy to add a [lifecycle badge](https://github.com/camunda-community-hub/community/blob/main/extension-lifecycle.md) to it indicating that the project is in need of a new maintainer.

I'm also more than happy to schedule a call and talk over this in more detail if that would be preferable to you, for whenever best suits your schedule over the next few weeks.

Thank you so much for your time. I look forward to hearing from you.

**Comment by amalagaura** [comment]
Hi Rin, yes I have no problem to move it over. I am reviewing some of the instructions there. I can transfer the repository and is there anything else I need to do?

**Comment by celanthe** [comment]
Hi @amalagaura! I just wanted to circle back on this and see if you were still interested in moving this extension into the Camunda Community Hub. For now I am going to close this issue, but feel free to re-open it if you'd like. Thank you so much.
